trigger:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildApplication
        displayName: Build the application
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK'
            inputs:
             version: '8.x'

          - script: 'dotnet restore'
            displayName: 'Restore'

          - script: 'dotnet build --configuration Release'
            displayName: 'Build'

          - task: PublishBuildArtifacts@1
            inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'build-output'
            publishLocation: 'Container'